version: '3.8'
services:
  blissmdb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: bliss
      MONGO_INITDB_ROOT_PASSWORD: bliss
    ports:
      - 27017:27017
    networks:
      - bliss_network

  # server:
  #   build: .
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - blissmdb
  #   networks:
  #     - blissmdb_network
  #   environment:
  #     DEV_DB_HOST: blissmdb

networks:
  bliss_network:
    driver: bridge
